apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-payment.servicename" . }}
  labels:
    {{- include "api-payment.labels" . | nindent 4 }}
    {{ include "api-payment.exposelabel" . }}: "true"
spec:
  type: {{ .Values.apiPayment.service.type }}
  selector:
    app: {{ include "api-payment.fullname" . }}
  ports:
    - port: {{ .Values.apiPayment.service.port }}
      targetPort: {{ .Values.apiPayment.service.port }}