apiPayment:
  replicaCount: 1

  image:
    registry: rookiesdogun/api-payment
    repository: payment-service
    tag: test
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080