apiVersion: v2
name: rookies-infra
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: metallb
    version: "0.13.10"  # 원하는 버전
    repository: "https://metallb.github.io/metallb"