apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookingredis.serviceName" . }}
  labels:
    app.kubernetes.io/name: {{ include "bookingredis.appName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ ( .Values.service | default (dict) ).type | default "ClusterIP" }}
  ports:
    - port: {{ ( .Values.service | default (dict) ).port | default 6379 }}
      targetPort: 6379
  selector:
    app.kubernetes.io/name: {{ include "bookingredis.appName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}