apiMessageTest:
  replicaCount: 1

  image:
    registry: rookiesdogun
    repository: kafka-message
    tag: test
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  database:
    host: api-festival-database-service
    port: 3306
    name: festival
    username: rookies
    password: rookies