apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiFestival.fullname" . }}
  labels:
    {{- include "apiFestival.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiFestival.service.type }}
  selector:
    app: {{ include "apiFestival.fullname" . }}
  ports:
    - port: {{ .Values.apiFestival.service.port }}
      targetPort: {{ .Values.apiFestival.service.port }}