global:
  service:
    kafka:  kafka-service
    kafkaUi:  kafka-ui-service
    apiGateway: api-gateway-service
    apiBooking: api-booking-service
    apiFestival: api-festival-service
    apiPayment: api-payment-service

    client: nginx-client-service
  apiGateway:
    serviceLabel: expose-via-spring-gateway

    
