apiBooking:
  replicaCount: 1

  image:
    registry: rookiesdogun
    repository: api-booking
    tag: test
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  database:
    host: api-booking-mariadb 
    port: 3306
    name: booking
    username: rookies
    password: rookies
  
  
api-booking-mariadb:
  auth:
    rootPassword: "rookies" 
    database: booking 
    username: rookies 
    password: rookies
  primary:
    service:
      name: api-booking-mariadb-service
      type: ClusterIP
  persistence:
    enabled: true
    size: 8Gi