replicaCount: 1

auth:
  rootPassword: "rookies"
  database: payment
  username: rookies
  password: rookies

service:
  name: api-payment-database-service
  type: ClusterIP
  port: 3306

persistence:
  enabled: true
  size: 8Gi
  storageClass: ""