apiFestival:
  replicaCount: 1

  image:
    registry: rookiesdogun/api-festival
    repository: festival-service
    tag: test
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080