apiVersion: v1
kind: Service
metadata:
  name: {{ include "apiBooking.fullname" . }}
  labels:
    {{- include "apiBooking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiBooking.service.type }}
  selector:
    app: {{ include "apiBooking.fullname" . }}
  ports:
    - port: {{ .Values.apiBooking.service.port }}
      targetPort: {{ .Values.apiBooking.service.port }}