apiVersion: v2
name: rookies-api
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: api-payment
    version: 0.1.0
    repository: file://charts/payment
  - name: api-booking
    version: 0.1.0
    repository: file://charts/booking
  - name: api-festival
    version: 0.1.0
    repository: file://charts/festival
  - name: api-gateway
    version: 0.1.0
    repository: file://charts/gateway
